import { Permission } from "./types";

export const CRITICAL_PERMISSIONS = [
  "organization:view",
  "organization:update",
  "organization:delete",
  "membership:view",
  "membership:update",
  "membership:delete",
  "invitation:view",
  "invitation:create",
  "invitation:delete",
] as const;

export const PERMISSION_LABELS = {
  "organization:delete": "Can Delete Organization",
  "organization:update": "Can Update Organization",
  "organization:view": "Can View Organization",
  "membership:delete": "Can Delete Membership",
  "membership:create": "Can Create Membership",
  "membership:update": "Can Update Membership",
  "membership:view": "Can View Membership",
  "ticket:delete": "Can Delete Ticket",
  "ticket:create": "Can Create Ticket",
  "ticket:update": "Can Update Ticket",
  "ticket:view": "Can View Ticket",
  "comment:delete": "Can Delete Comment",
  "comment:create": "Can Create Comment",
  "comment:update": "Can Update Comment",
  "comment:view": "Can View Comment",
  "attachment:delete": "Can Delete Attachment",
  "attachment:create": "Can Create Attachment",
  "attachment:update": "Can Update Attachment",
  "attachment:view": "Can View Attachment",
  "invitation:delete": "Can Delete Invitation",
  "invitation:create": "Can Create Invitation",
  "invitation:view": "Can View Invitation",
} as const;

// Default membership role permissions used for seeding purposes
export const MEMBER_ROLE_PERMISSIONS: Permission = {
  "organization:delete": false,
  "organization:update": false,
  "organization:view": true,
  "membership:delete": false,
  "membership:create": false,
  "membership:update": false,
  "membership:view": true,
  "ticket:delete": false,
  "ticket:create": true,
  "ticket:update": true,
  "ticket:view": true,
  "comment:delete": false,
  "comment:create": true,
  "comment:update": true,
  "comment:view": true,
  "attachment:delete": false,
  "attachment:create": true,
  "attachment:update": true,
  "attachment:view": true,
  "invitation:delete": false,
  "invitation:create": false,
  "invitation:view": true,
};

export const ADMIN_ROLE_PERMISSIONS: Permission = {
  "organization:delete": true,
  "organization:update": true,
  "organization:view": true,
  "membership:delete": true,
  "membership:create": true,
  "membership:update": true,
  "membership:view": true,
  "ticket:delete": true,
  "ticket:create": true,
  "ticket:update": true,
  "ticket:view": true,
  "comment:delete": true,
  "comment:create": true,
  "comment:update": true,
  "comment:view": true,
  "attachment:delete": true,
  "attachment:create": true,
  "attachment:update": true,
  "attachment:view": true,
  "invitation:delete": true,
  "invitation:create": true,
  "invitation:view": true,
};
